apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart: prometheus-community/kube-prometheus-stack
  targetNamespace: monitoring
  set:
    grafana.adminPassword: "admin123"
    prometheus.service.type: LoadBalancer
    grafana.service.type: LoadBalancer
