sonar.projectKey=momo-store
sonar.projectName=Momo Store
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/test/**
sonar.tests=.
sonar.test.inclusions=**/*test*/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.go.coverage.reportPaths=coverage.out
