apiVersion: v1
entries:
  momo-store:
  - annotations:
      artifacthub.io/links: |
        - name: Momo Store GitHub
          url: https://github.com/your-org/momo-store
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.0.0
    created: "2025-09-28T01:17:50.991724191+03:00"
    description: Helm chart for Momo Store E-commerce Application
    digest: 5b3dbd82cfe8e867e8af2f26122d4790a2834f15d95d0d0fef91b364dd0d7dce
    maintainers:
    - email: student@example.com
      name: Student
    name: momo-store
    type: application
    urls:
    - https://nexus.praktikum-services.tech/repository/std-039-27-helm/momo-store-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-28T01:17:50.990971098+03:00"
